[versions]
jdk = "11"
checkstyle = "10.17.0"

[plugins]
git-publish = "org.ajoberstar.git-publish:4.2.2"
pages = "com.hanggrian.pages:0.1"

[libraries]
# lint
rulebook-checkstyle = "com.hanggrian.rulebook:rulebook-checkstyle:0.1"
# main
# test
truth = "com.google.truth:truth:1.4.4"
