[versions]
java-compile = "21"
java-support = "8"
checkstyle = "11.1.0"

[plugins]
gradle-publish = "com.gradle.plugin-publish:2.1.0"
git-publish = "org.ajoberstar.git-publish:5.1.3"
pages = "com.hanggrian.pages:0.3"

[libraries]
# lint
rulebook-checkstyle = "com.hanggrian.rulebook:rulebook-checkstyle:0.2"
# main
# test
junit = "junit:junit:4.13.2"
mockito-core = "org.mockito:mockito-core:5.23.0"
truth = "com.google.truth:truth:1.4.5"

[bundles]
junit4 = [
  "junit",
  "mockito-core",
  "truth",
]
